### PR TITLE
Update wiremock version to 2.33.2

### PR DESCRIPTION
**Pull request by github-olivier-sos**

### CODE REVIEW

**Comment by ismail-chafai** [comment]
Hello @github-olivier-sos , is this bump blocking you ? 

Since it is platform team that owns service-wiremock, we are trying to understand if this repo wiremock-extensions is only used by the SSP team or more globally. If it is used more globally, we'll discuss with the platform team if they want to take ownership. If it is only used by the SSP team, we'll take ownership of it.

(cc @github-christophe-oudar)

**Comment by github-olivier-sos** [comment]
Hello @github-ismail-chafai ,
I bumped [this repo](https://github.com/ebuzzing/service-wiremock/blob/master/Dockerfile) since I needed a higher version for wiremock.
I just wanted to keep the version the same on the 2 repos.
But don't really know if it's necessary.

**Comment by github-christophe-oudar** [comment]
As this repository is public (teads org), I'll just approve & merge
Due to the little volume of changes, I guess we can make do with the current status.

**Review by github-christophe-oudar — APPROVED** [review]

**Comment by github-christophe-oudar** [comment]
I can't build the project and the CI doesn't pass.
I think we probably need to bump SBT and some other parts.
I could be nice if another could check it's not breaking anything, cc @Viewtiful @nailyk, thanks!

**Review by github-kylian-deau — APPROVED** [review]

**Pull request closed without merging**
