### PR TITLE
Add Travis CI configuration

### PR DESCRIPTION
**Pull request by pdalpra**

### CODE REVIEW

**Comment by AlixBa** [comment]
do your magic here :fire:

**Comment by AlixBa** [comment]
don't forget to update the readme with a new badge (I guess we will not use Jenkins anymore)

**Comment by pdalpra** [comment]
indeed :)

**Comment by pdalpra** [comment]
my bad, don't know why I merged directly...
LGTM ? :D

**Comment by AlixBa** [comment]
LGTY apparently :D

**Pull request merged**
